services:
  - type: web
    name: horse-electricals
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn horse_site.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER
        value: True